name: CSV AI Safety Tweet Generator

on:
  schedule:
    # Run at 6:00 AM JST daily (21:00 UTC)
    - cron: '0 21 * * *'
  workflow_dispatch:

jobs:
  csv-ai-safety-tweet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate and Post CSV AI Safety Tweet
        env:
          TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
          TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
        run: python csv_tweet_generator.py

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: csv-ai-safety-tweet-logs-${{ github.run_number }}
          path: |
            *.log
            logs/
          retention-days: 30